"""Complete 150-Core registry for SHADOW Super Nice."""
from __future__ import annotations
from .contracts import CoreSpec, Risk

CORE_SPECS=(
    CoreSpec("CORE-001","Identity","identity","Master identity and authority context.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-002","Conversation","conversation","Unified text and voice conversation state.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-003","Reasoning","reasoning","Controlled decomposition and inference.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-004","Memory","memory","Governed durable memory and recall.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-005","Personal Understanding","personal","Personal context and preferences.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-006","Web Discovery","web","Web discovery and source retrieval.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-007","GitHub / Development","github","Governed repository and development capabilities.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-008","Integration Engine","integration","Adapter lifecycle, health and rollback.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-009","Companion","companion","Companion trust and lifecycle.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-010","Device / Environment","device","Semantic device and environment understanding.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-011","Spatial","spatial","Privacy-preserving semantic spatial model.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-012","Action / Security / Approval","security","Governed action execution and approval.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-013","Multi-Model Router","intelligence","Bounded multi-model router capability behind the shared Shadow contract.",risk=Risk.LOW,requires_confirmation=False),
    CoreSpec("CORE-014","Model Capability Resolver","intelligence","Bounded model capability resolver capability behind the shared Shadow contract.",risk=Risk.LOW,requires_confirmation=False),
    CoreSpec("CORE-015","Provider Health","intelligence","Bounded provider health capability behind the shared Shadow contract.",risk=Risk.LOW,requires_confirmation=False),
    CoreSpec("CORE-016","Free-First Cost Policy","intelligence","Bounded free-first cost policy capability behind the shared Shadow contract.",risk=Risk.LOW,requires_confirmation=False),
    CoreSpec("CORE-017","Ensemble Reasoning","intelligence","Bounded ensemble reasoning capability behind the shared Shadow contract.",risk=Risk.LOW,requires_confirmation=False),
    CoreSpec("CORE-018","Debate & Consensus","intelligence","Bounded debate & consensus capability behind the shared Shadow contract.",risk=Risk.LOW,requires_confirmation=False),
    CoreSpec("CORE-019","Context Compression","intelligence","Bounded context compression capability behind the shared Shadow contract.",risk=Risk.LOW,requires_confirmation=False),
    CoreSpec("CORE-020","Long-Context Manager","intelligence","Bounded long-context manager capability behind the shared Shadow contract.",risk=Risk.LOW,requires_confirmation=False),
    CoreSpec("CORE-021","Structured Reasoning","intelligence","Bounded structured reasoning capability behind the shared Shadow contract.",risk=Risk.LOW,requires_confirmation=False),
    CoreSpec("CORE-022","Hypothesis Manager","intelligence","Bounded hypothesis manager capability behind the shared Shadow contract.",risk=Risk.LOW,requires_confirmation=False),
    CoreSpec("CORE-023","Uncertainty Calibration","intelligence","Bounded uncertainty calibration capability behind the shared Shadow contract.",risk=Risk.LOW,requires_confirmation=False),
    CoreSpec("CORE-024","Answer Composer","intelligence","Bounded answer composer capability behind the shared Shadow contract.",risk=Risk.LOW,requires_confirmation=False),
    CoreSpec("CORE-025","Semantic Memory","intelligence","Bounded semantic memory capability behind the shared Shadow contract.",risk=Risk.LOW,requires_confirmation=False),
    CoreSpec("CORE-026","Episodic Memory","memory","Bounded episodic memory capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-027","Event Memory","memory","Bounded event memory capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-028","Personal Knowledge Graph","memory","Bounded personal knowledge graph capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-029","Temporal Memory","memory","Bounded temporal memory capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-030","Memory Consolidation","memory","Bounded memory consolidation capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-031","Memory Retention","memory","Bounded memory retention capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-032","Forget & Deletion","memory","Bounded forget & deletion capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-033","Memory Permissions","memory","Bounded memory permissions capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-034","Memory Provenance","memory","Bounded memory provenance capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-035","Conversation Recall","memory","Bounded conversation recall capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-036","Preference Learning","memory","Bounded preference learning capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-037","Correction Learning","memory","Bounded correction learning capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-038","Legacy Memory","memory","Bounded legacy memory capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-039","Memory Integrity","memory","Bounded memory integrity capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-040","Personal Context Engine","memory","Bounded personal context engine capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-041","Reminder Intelligence","personal_execution","Bounded reminder intelligence capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-042","Habit Context","personal_execution","Bounded habit context capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-043","Life Timeline","personal_execution","Bounded life timeline capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-044","Relationship Context","personal_execution","Bounded relationship context capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-045","Emotional Signal Context","personal_execution","Bounded emotional signal context capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-046","Conversation State","personal_execution","Bounded conversation state capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-047","Attention Prioritizer","personal_execution","Bounded attention prioritizer capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-048","Task Manager","personal_execution","Bounded task manager capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-049","Goal Decomposer","personal_execution","Bounded goal decomposer capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-050","Master Planner","personal_execution","Bounded master planner capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-051","Dependency Planner","personal_execution","Bounded dependency planner capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-052","Schedule Planner","personal_execution","Bounded schedule planner capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-053","Deadline Monitor","personal_execution","Bounded deadline monitor capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-054","Retry & Recovery","personal_execution","Bounded retry & recovery capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-055","Checkpoint Manager","personal_execution","Bounded checkpoint manager capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-056","Rollback Manager","personal_execution","Bounded rollback manager capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-057","Execution Verifier","personal_execution","Bounded execution verifier capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-058","Evidence Verifier","personal_execution","Bounded evidence verifier capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-059","Source Trust","personal_execution","Bounded source trust capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-060","Freshness Resolver","personal_execution","Bounded freshness resolver capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-061","Contradiction Resolver","personal_execution","Bounded contradiction resolver capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-062","Fact vs Inference","personal_execution","Bounded fact vs inference capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-063","Citation Manager","personal_execution","Bounded citation manager capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-064","Research Planner","personal_execution","Bounded research planner capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-065","Web Search","personal_execution","Bounded web search capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-066","Web Fetch","research","Bounded web fetch capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-067","Document Analyzer","research","Bounded document analyzer capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-068","PDF Analyzer","research","Bounded pdf analyzer capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-069","Spreadsheet Analyzer","research","Bounded spreadsheet analyzer capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-070","Workspace Files","research","Bounded workspace files capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-071","Archive & ZIP Analyzer","research","Bounded archive & zip analyzer capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-072","OCR","research","Bounded ocr capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-073","Translation","research","Bounded translation capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-074","Language Detection","research","Bounded language detection capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-075","Code Understanding","research","Bounded code understanding capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-076","Code Generation","research","Bounded code generation capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-077","Code Refactor","research","Bounded code refactor capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-078","Test Generator","research","Bounded test generator capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-079","Build Orchestrator","software","Bounded build orchestrator capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-080","CI Diagnoser","software","Bounded ci diagnoser capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-081","GitHub Adapter","software","Bounded github adapter capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-082","Git Branch Manager","software","Bounded git branch manager capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-083","Patch Planner","software","Bounded patch planner capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-084","Diff Reviewer","software","Bounded diff reviewer capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-085","Dependency Auditor","software","Bounded dependency auditor capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-086","Security Scanner","software","Bounded security scanner capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-087","Secret Detector","software","Bounded secret detector capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-088","License & Attribution Auditor","software","Bounded license & attribution auditor capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-089","Package Manager","software","Bounded package manager capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-090","App Generator","software","Bounded app generator capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-091","Web App Builder","software","Bounded web app builder capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-092","Desktop App Builder","software","Bounded desktop app builder capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-093","Mobile App Builder","software","Bounded mobile app builder capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-094","Game Systems Builder","software","Bounded game systems builder capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-095","2D Asset Builder","software","Bounded 2d asset builder capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-096","3D Asset Pipeline","software","Bounded 3d asset pipeline capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-097","Scene & Level Planner","software","Bounded scene & level planner capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-098","Game Balance Analyzer","software","Bounded game balance analyzer capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-099","Image Understanding","multimodal","Bounded image understanding capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-100","Image Generation Adapter","multimodal","Bounded image generation adapter capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-101","Image Edit Adapter","multimodal","Bounded image edit adapter capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-102","Video Understanding","multimodal","Bounded video understanding capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-103","Video Generation Adapter","multimodal","Bounded video generation adapter capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-104","Audio Understanding","multimodal","Bounded audio understanding capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-105","Speech-to-Text","multimodal","Bounded speech-to-text capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-106","Text-to-Speech","multimodal","Bounded text-to-speech capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-107","Voice Identity","multimodal","Bounded voice identity capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-108","Wake Word","multimodal","Bounded wake word capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-109","Live Conversation","multimodal","Bounded live conversation capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-110","Streaming Conversation","multimodal","Bounded streaming conversation capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-111","Multimodal Fusion","multimodal","Bounded multimodal fusion capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-112","Screen Understanding","multimodal","Bounded screen understanding capability behind the shared Shadow contract.",risk=Risk.MEDIUM,requires_confirmation=False),
    CoreSpec("CORE-113","Device Registry","devices_spatial","Bounded device registry capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-114","Device Capability Discovery","devices_spatial","Bounded device capability discovery capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-115","Bluetooth & BLE","devices_spatial","Bounded bluetooth & ble capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-116","Wi-Fi Discovery","devices_spatial","Bounded wi-fi discovery capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-117","NFC","devices_spatial","Bounded nfc capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-118","Camera & Sensor Semantics","devices_spatial","Bounded camera & sensor semantics capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-119","Semantic Location","devices_spatial","Bounded semantic location capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-120","Proximity & Direction","devices_spatial","Bounded proximity & direction capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-121","Environment State","devices_spatial","Bounded environment state capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-122","Physics & Simulation","devices_spatial","Bounded physics & simulation capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-123","Math & Quant","devices_spatial","Bounded math & quant capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-124","Measurement & Units","devices_spatial","Bounded measurement & units capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-125","Smart Home Adapter","devices_spatial","Bounded smart home adapter capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-126","Car Adapter","devices_spatial","Bounded car adapter capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-127","Wearable Adapter","devices_spatial","Bounded wearable adapter capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-128","Companion Registry","devices_spatial","Bounded companion registry capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-129","Companion Trust","devices_spatial","Bounded companion trust capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-130","Companion Task Delegation","devices_spatial","Bounded companion task delegation capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-131","Companion Audit","devices_spatial","Bounded companion audit capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-132","Cross-Core Event Bus","governance_integration","Bounded cross-core event bus capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-133","Workflow Engine","governance_integration","Bounded workflow engine capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-134","Rule Engine","governance_integration","Bounded rule engine capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-135","Policy Engine","governance_integration","Bounded policy engine capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-136","Permission Manager","governance_integration","Bounded permission manager capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-137","Safety Guardrails","governance_integration","Bounded safety guardrails capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-138","Sandboxing","governance_integration","Bounded sandboxing capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-139","Secrets Vault Interface","governance_integration","Bounded secrets vault interface capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-140","Audit Log","governance_integration","Bounded audit log capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-141","Threat Detection","governance_integration","Bounded threat detection capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-142","Rate Limiter","governance_integration","Bounded rate limiter capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-143","Data Minimization","governance_integration","Bounded data minimization capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-144","Privacy Controls","governance_integration","Bounded privacy controls capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-145","Emergency Shutdown","governance_integration","Bounded emergency shutdown capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-146","Self-Diagnostics","governance_integration","Bounded self-diagnostics capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-147","Self-Evolution Planner","governance_integration","Bounded self-evolution planner capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-148","Self-Evolution Sandbox","governance_integration","Bounded self-evolution sandbox capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-149","Capability & Plugin Installer","governance_integration","Bounded capability & plugin installer capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
    CoreSpec("CORE-150","Legacy Continuity & Delivery","governance_integration","Bounded legacy continuity & delivery capability behind the shared Shadow contract.",risk=Risk.HIGH,requires_confirmation=True),
)
CORE_BY_ID={s.id:s for s in CORE_SPECS}
assert len(CORE_SPECS)==150 and len(CORE_BY_ID)==150
