import express from 'express';
import helmet from 'helmet';
import cors from 'cors';
import { applyFiles, status as developmentStatus } from './development-agent.mjs';
import { startDeviceAuthorization, pollDeviceAuthorization, status as githubOAuthStatus } from './github-oauth.mjs';
import { voiceprintStatus, verifyVoiceprint } from './voiceprint.mjs';
import { runAgent, agentStatus } from './agent.mjs';

const app = express();
const port = Number(process.env.PORT || 8787);
const apiKey = String(process.env.OPENAI_API_KEY || '').trim();
const model = String(process.env.OPENAI_MODEL || 'gpt-5-mini').trim();
const imageModel = String(process.env.OPENAI_IMAGE_MODEL || 'gpt-image-1').trim();
const ttsModel = String(process.env.SHADOW_TTS_MODEL || 'gpt-4o-mini-tts').trim();
const ttsVoice = String(process.env.SHADOW_TTS_VOICE || 'onyx').trim();
const ttsVoiceId = String(process.env.SHADOW_TTS_VOICE_ID || '').trim();
const ttsInstructions = String(process.env.SHADOW_TTS_INSTRUCTIONS || 'Speak with a refined, cinematic, futuristic British AI-assistant character: deep adult male voice, calm authority, precise diction, restrained emotion, intelligent and composed, slightly warm, measured pacing, subtle dry confidence. This is an original Jarvis-inspired delivery, not an imitation of any actor or copyrighted character performance. When speaking Egyptian Arabic (ar-EG), keep the same deep, polished, controlled delivery while using natural Egyptian pronunciation and vocabulary.').trim();
const systemPrompt = String(process.env.SHADOW_SYSTEM_PROMPT || 'You are SHADOW, a personal Android AI assistant. Use natural Egyptian Arabic for Arabic users. Never claim external actions unless confirmed. One unified command surface; offline is an internal fallback only.').trim();

app.disable('x-powered-by');
app.use(helmet());
app.use(cors({ origin: true, methods: ['GET','POST','OPTIONS'], allowedHeaders: ['Content-Type','Authorization'] }));
app.use(express.json({ limit: '20mb' }));
const buckets = new Map();
function rateLimit(req,res,next){const key=req.ip||'unknown',now=Date.now(),windowMs=60_000,max=30,old=buckets.get(key);if(!old||now-old.started>=windowMs){buckets.set(key,{started:now,count:1});return next();}old.count+=1;if(old.count>max)return res.status(429).json({ok:false,error:'rate_limited'});return next();}

app.get('/health',(_req,res)=>res.json({ok:true,service:'shadow-cloud',online:Boolean(apiKey),model,image_model:imageModel,agent:agentStatus(),system_prompt_configured:Boolean(systemPrompt),tts_model:ttsModel,tts_voice:ttsVoice,tts_voice_id_configured:Boolean(ttsVoiceId),tts_voice_mode:ttsVoiceId?'custom':'built_in',tts_locale:'ar-EG',tts_gender:'male',tts_style:'jarvis-inspired-original',web_search:true,development_agent:true,development_writer:developmentStatus(),github_authorization:githubOAuthStatus(),image_generation:true,voiceprint:voiceprintStatus()}));

app.post('/v1/chat',rateLimit,async(req,res)=>{if(!apiKey)return res.status(503).json({ok:false,error:'backend_not_configured'});const message=typeof req.body?.message==='string'?req.body.message.trim():'';if(!message)return res.status(400).json({ok:false,error:'message_required'});if(message.length>12000)return res.status(413).json({ok:false,error:'message_too_large'});const previousResponseId=typeof req.body?.previous_response_id==='string'&&req.body.previous_response_id.trim()?req.body.previous_response_id.trim():undefined;const device=typeof req.body?.device==='string'?req.body.device.slice(0,16000):'';try{const result=await runAgent({message,previousResponseId,deviceProfile:device,maxTurns:8});return res.json({ok:true,...result});}catch(error){const msg=String(error?.message||'ai_request_failed');console.error('Unified agent failed',msg);if(msg==='ai_credits_exhausted')return res.status(503).json({ok:false,error:msg});if(msg==='backend_not_configured')return res.status(503).json({ok:false,error:msg});if(msg==='empty_ai_response')return res.status(502).json({ok:false,error:msg});return res.status(502).json({ok:false,error:msg.startsWith('upstream_ai_error_')?msg:'ai_unreachable'});}});

app.post('/v1/github/device/start',rateLimit,async(_req,res)=>{try{return res.json({ok:true,...await startDeviceAuthorization()});}catch(error){const msg=String(error?.message||'github_oauth_failed');return res.status(msg==='github_oauth_not_configured'?503:502).json({ok:false,error:msg});}});
app.post('/v1/github/device/poll',rateLimit,async(req,res)=>{try{const deviceCode=typeof req.body?.device_code==='string'?req.body.device_code.trim():'';if(!deviceCode)return res.status(400).json({ok:false,error:'device_code_required'});return res.json({ok:true,...await pollDeviceAuthorization(deviceCode)});}catch(error){return res.status(502).json({ok:false,error:String(error?.message||'github_oauth_failed')});}});
app.post('/v1/voiceprint/verify',rateLimit,async(req,res)=>{try{const audioBase64=typeof req.body?.audio_base64==='string'?req.body.audio_base64.trim():'';const contentType=typeof req.body?.content_type==='string'?req.body.content_type.slice(0,80):'audio/wav';const result=await verifyVoiceprint(audioBase64,contentType);if(result.verified!==true)return res.status(401).json({ok:false,...result});return res.json({ok:true,...result});}catch(error){const msg=String(error?.message||'voiceprint_failed');const status=msg==='voiceprint_provider_not_configured'?503:msg==='audio_required'||msg==='audio_invalid'||msg==='audio_too_large'?400:502;return res.status(status).json({ok:false,error:msg});}});
app.post('/v1/development/plan',rateLimit,async(req,res)=>{if(!apiKey)return res.status(503).json({ok:false,error:'backend_not_configured'});const request=typeof req.body?.request==='string'?req.body.request.trim():'';const project=typeof req.body?.project==='string'?req.body.project.slice(0,12000):'';if(!request)return res.status(400).json({ok:false,error:'request_required'});try{const result=await runAgent({message:`Create a safe software implementation plan for this request. Do not claim edits executed. Return JSON-like plain text with summary, files, risks, tests, approval_required. Request: ${request}\nProject: ${project}`,maxTurns:4});return res.json({ok:true,plan:result.answer,approval_required:true,execution_available:developmentStatus().configured,reason:developmentStatus().configured?'explicit_approval_required':'github_write_not_configured'});}catch(error){return res.status(502).json({ok:false,error:String(error?.message||'development_unreachable')});}});
app.post('/v1/development/apply',rateLimit,async(req,res)=>{if(req.body?.approved!==true)return res.status(403).json({ok:false,error:'explicit_approval_required'});const branch=typeof req.body?.branch==='string'&&/^[A-Za-z0-9._/-]{1,80}$/.test(req.body.branch)?req.body.branch:'shadow-agent-work';const message=typeof req.body?.commit_message==='string'&&req.body.commit_message.trim()?req.body.commit_message.trim().slice(0,160):'SHADOW agent change';const token=typeof req.body?.github_token==='string'?req.body.github_token.trim():'';try{const result=await applyFiles({branch,message,files:req.body?.files,token});return res.json({ok:true,executed:true,result});}catch(error){const msg=String(error?.message||'development_apply_failed');return res.status(msg==='github_write_not_configured'?503:400).json({ok:false,error:msg});}});
app.post('/v1/images',rateLimit,async(req,res)=>{if(!apiKey)return res.status(503).json({ok:false,error:'backend_not_configured'});const prompt=typeof req.body?.prompt==='string'?req.body.prompt.trim():'';if(!prompt)return res.status(400).json({ok:false,error:'prompt_required'});if(prompt.length>8000)return res.status(413).json({ok:false,error:'prompt_too_large'});try{const upstream=await fetch('https://api.openai.com/v1/images/generations',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:imageModel,prompt,size:'1024x1024'}),signal:AbortSignal.timeout(120000)});const body=await upstream.json().catch(()=>({}));if(!upstream.ok)return res.status(502).json({ok:false,error:'image_upstream_error'});const b64=body?.data?.[0]?.b64_json;if(typeof b64!=='string'||!b64)return res.status(502).json({ok:false,error:'empty_image'});return res.json({ok:true,image_base64:b64,model:imageModel});}catch{return res.status(502).json({ok:false,error:'image_unreachable'});}});
app.post('/v1/speech',rateLimit,async(req,res)=>{if(!apiKey)return res.status(503).json({ok:false,error:'backend_not_configured'});const input=typeof req.body?.input==='string'?req.body.input.trim():'';if(!input)return res.status(400).json({ok:false,error:'input_required'});if(input.length>4096)return res.status(413).json({ok:false,error:'input_too_large'});const voice=ttsVoiceId?{id:ttsVoiceId}:ttsVoice;try{const upstream=await fetch('https://api.openai.com/v1/audio/speech',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:ttsModel,voice,input,instructions:ttsInstructions,response_format:'mp3'}),signal:AbortSignal.timeout(60000)});if(!upstream.ok)return res.status(502).json({ok:false,error:'speech_upstream_error'});const buffer=Buffer.from(await upstream.arrayBuffer());res.set('Content-Type','audio/mpeg');res.set('Cache-Control','no-store');res.set('X-SHADOW-TTS-Mode',ttsVoiceId?'custom':'built-in');res.set('X-SHADOW-TTS-Style','jarvis-inspired-original');return res.send(buffer);}catch{return res.status(502).json({ok:false,error:'speech_unreachable'});}});
app.listen(port,'0.0.0.0',()=>console.log(`SHADOW cloud backend listening on ${port}; model=${model}; agent=unified; tts=${ttsModel}/${ttsVoice}; tts_style=jarvis-inspired-original`));
