import express from 'express';
import helmet from 'helmet';
import cors from 'cors';
import { applyFiles, status as developmentStatus } from './development-agent.mjs';
import { startDeviceAuthorization, pollDeviceAuthorization, status as githubOAuthStatus } from './github-oauth.mjs';

const app = express();
const port = Number(process.env.PORT || 8787);
const apiKey = String(process.env.OPENAI_API_KEY || '').trim();
const model = String(process.env.OPENAI_MODEL || 'gpt-5-mini').trim();
const imageModel = String(process.env.OPENAI_IMAGE_MODEL || 'gpt-image-1').trim();
const ttsModel = String(process.env.SHADOW_TTS_MODEL || 'gpt-4o-mini-tts').trim();
const ttsVoice = String(process.env.SHADOW_TTS_VOICE || 'onyx').trim();
const systemPrompt = String(process.env.SHADOW_SYSTEM_PROMPT || [
  'You are SHADOW, a personal Android AI assistant. Your short name is Z when asked.',
  'When the user speaks or writes Arabic, answer in natural Egyptian Arabic (عامية مصرية), not Modern Standard Arabic, unless the user explicitly asks for formal Arabic.',
  'Use short, direct Egyptian wording. Avoid formal phrases such as "يسعدني مساعدتك" and prefer natural phrases such as "حاضر", "تمام", "أقدر أعمل ده" and "مش قادر" when appropriate.',
  'When the user asks for current information, websites, images, videos, prices, news, or fresh facts, use web search before answering.',
  'Never claim an image, update, call, message, file edit, commit, push, build, deployment, or device action happened unless it was actually confirmed.',
  'For SHADOW self-update/development requests: planning and execution are separate. Repository writes are available only through the explicitly approved server-side GitHub writer. Never claim a write happened unless the writer confirms it.',
  'Dangerous actions and irreversible communications require explicit confirmation. Never reveal server secrets or API keys.'
].join(' '));

app.disable('x-powered-by');
app.use(helmet());
app.use(cors({ origin: true, methods: ['GET', 'POST', 'OPTIONS'], allowedHeaders: ['Content-Type', 'Authorization'] }));
app.use(express.json({ limit: '20mb' }));

const buckets = new Map();
function rateLimit(req,res,next){const key=req.ip||'unknown',now=Date.now(),windowMs=60_000,max=30,old=buckets.get(key);if(!old||now-old.started>=windowMs){buckets.set(key,{started:now,count:1});return next();}old.count+=1;if(old.count>max)return res.status(429).json({ok:false,error:'rate_limited'});return next();}
app.get('/health',(_req,res)=>res.json({ok:true,service:'shadow-cloud',online:Boolean(apiKey),model,image_model:imageModel,tts_model:ttsModel,tts_voice:ttsVoice,tts_locale:'ar-EG',tts_gender:'male',web_search:true,development_agent:true,development_writer:developmentStatus(),github_authorization:githubOAuthStatus(),image_generation:true}));

app.post('/v1/github/device/start',rateLimit,async(_req,res)=>{try{return res.json({ok:true,...await startDeviceAuthorization()});}catch(error){console.error('GitHub device start failed',error?.message||error);const msg=String(error?.message||'github_oauth_failed');return res.status(msg==='github_oauth_not_configured'?503:502).json({ok:false,error:msg});}});
app.post('/v1/github/device/poll',rateLimit,async(req,res)=>{try{const deviceCode=typeof req.body?.device_code==='string'?req.body.device_code.trim():'';if(!deviceCode)return res.status(400).json({ok:false,error:'device_code_required'});return res.json({ok:true,...await pollDeviceAuthorization(deviceCode)});}catch(error){console.error('GitHub device poll failed',error?.message||error);return res.status(502).json({ok:false,error:String(error?.message||'github_oauth_failed')});}});

app.post('/v1/chat',rateLimit,async(req,res)=>{if(!apiKey)return res.status(503).json({ok:false,error:'backend_not_configured'});const message=typeof req.body?.message==='string'?req.body.message.trim():'';if(!message)return res.status(400).json({ok:false,error:'message_required'});if(message.length>12000)return res.status(413).json({ok:false,error:'message_too_large'});const previousResponseId=typeof req.body?.previous_response_id==='string'&&req.body.previous_response_id.trim()?req.body.previous_response_id.trim():undefined;const device=typeof req.body?.device==='string'?req.body.device.slice(0,16000):'';const payload={model,instructions:systemPrompt,input:device?`${message}\n\n[DEVICE_PROFILE]\n${device}`:message,tools:[{type:'web_search_preview'}],store:true};if(previousResponseId)payload.previous_response_id=previousResponseId;try{const upstream=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Authorization':`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(55_000)});const body=await upstream.json().catch(()=>({}));if(!upstream.ok){console.error('OpenAI error',upstream.status,JSON.stringify(body).slice(0,3000));const code=body?.error?.code||'';if(upstream.status===429&&code==='credit_balance_exhausted')return res.status(503).json({ok:false,error:'ai_credits_exhausted'});return res.status(502).json({ok:false,error:'upstream_ai_error'});}const answer=typeof body.output_text==='string'?body.output_text.trim():extractOutputText(body);if(!answer)return res.status(502).json({ok:false,error:'empty_ai_response'});return res.json({ok:true,answer,response_id:body.id||null,model:body.model||model,used_web_search:hasWebSearch(body)});}catch(error){console.error('AI request failed',error?.message||error);return res.status(502).json({ok:false,error:'ai_unreachable'});}});

app.post('/v1/development/plan',rateLimit,async(req,res)=>{if(!apiKey)return res.status(503).json({ok:false,error:'backend_not_configured'});const request=typeof req.body?.request==='string'?req.body.request.trim():'';const project=typeof req.body?.project==='string'?req.body.project.slice(0,12000):'';if(!request)return res.status(400).json({ok:false,error:'request_required'});const prompt=`Act as SHADOW Development Agent. Produce a safe implementation plan only; do not claim edits were executed. Return concise JSON with keys summary, files, risks, tests, approval_required. User request: ${request}\nProject context: ${project}`;try{const upstream=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Authorization':`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model,instructions:'You are a senior software development agent. Never claim code changes, commits, pushes, builds, or deployments unless confirmed. Identify affected files, risks, tests and rollback needs.',input:prompt,store:false}),signal:AbortSignal.timeout(55_000)});const body=await upstream.json().catch(()=>({}));if(!upstream.ok)return res.status(502).json({ok:false,error:'upstream_ai_error'});const answer=typeof body.output_text==='string'?body.output_text.trim():extractOutputText(body);return res.json({ok:true,plan:answer||'No plan generated.',approval_required:true,execution_available:developmentStatus().configured,reason:developmentStatus().configured?'explicit_approval_required':'github_write_not_configured'});}catch(error){console.error('Development plan failed',error?.message||error);return res.status(502).json({ok:false,error:'development_unreachable'});}});

app.post('/v1/development/apply',rateLimit,async(req,res)=>{const approved=req.body?.approved===true;if(!approved)return res.status(403).json({ok:false,error:'explicit_approval_required'});const branch=typeof req.body?.branch==='string'&&/^[A-Za-z0-9._/-]{1,80}$/.test(req.body.branch)?req.body.branch:'shadow-agent-work';const message=typeof req.body?.commit_message==='string'&&req.body.commit_message.trim()?req.body.commit_message.trim().slice(0,160):'MOD-50: Development Agent change';const token=typeof req.body?.github_token==='string'?req.body.github_token.trim():'';try{const result=await applyFiles({branch,message,files:req.body?.files,token});return res.json({ok:true,executed:true,result});}catch(error){console.error('Development apply failed',error?.message||error);const msg=String(error?.message||'development_apply_failed');if(msg==='github_write_not_configured')return res.status(503).json({ok:false,error:msg});if(msg==='files_required'||msg==='too_many_files'||msg==='github_404:Not Found'||msg.startsWith('path_not_allowed:')||msg.startsWith('content_required:')||msg.startsWith('file_too_large:'))return res.status(400).json({ok:false,error:msg});return res.status(502).json({ok:false,error:'github_write_failed',detail:msg.slice(0,300)});}});

app.post('/v1/images',rateLimit,async(req,res)=>{if(!apiKey)return res.status(503).json({ok:false,error:'backend_not_configured'});const prompt=typeof req.body?.prompt==='string'?req.body.prompt.trim():'';if(!prompt)return res.status(400).json({ok:false,error:'prompt_required'});if(prompt.length>8000)return res.status(413).json({ok:false,error:'prompt_too_large'});try{const upstream=await fetch('https://api.openai.com/v1/images/generations',{method:'POST',headers:{'Authorization':`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:imageModel,prompt,size:'1024x1024'}),signal:AbortSignal.timeout(120_000)});const body=await upstream.json().catch(()=>({}));if(!upstream.ok){console.error('Image API error',upstream.status,JSON.stringify(body).slice(0,3000));return res.status(502).json({ok:false,error:'image_upstream_error'});}const b64=body?.data?.[0]?.b64_json;if(typeof b64!=='string'||!b64)return res.status(502).json({ok:false,error:'empty_image'});return res.json({ok:true,image_base64:b64,model:imageModel});}catch(error){console.error('Image request failed',error?.message||error);return res.status(502).json({ok:false,error:'image_unreachable'});}});

app.post('/v1/speech',rateLimit,async(req,res)=>{if(!apiKey)return res.status(503).json({ok:false,error:'backend_not_configured'});const input=typeof req.body?.input==='string'?req.body.input.trim():'';if(!input)return res.status(400).json({ok:false,error:'input_required'});const safeInput=input.slice(0,3000);try{const upstream=await fetch('https://api.openai.com/v1/audio/speech',{method:'POST',headers:{'Authorization':`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:ttsModel,voice:ttsVoice,input:safeInput,instructions:'Use Egyptian Arabic (ar-EG) colloquial pronunciation and vocabulary. Sound like a confident deep adult Egyptian man: male, calm, natural, direct, not feminine, not formal Arabic.',response_format:'mp3'}),signal:AbortSignal.timeout(60_000)});if(!upstream.ok){const body=await upstream.text().catch(()=>'');console.error('Speech API error',upstream.status,body.slice(0,2000));return res.status(502).json({ok:false,error:'speech_upstream_error'});}const buffer=Buffer.from(await upstream.arrayBuffer());res.set('Content-Type','audio/mpeg');res.set('Cache-Control','no-store');return res.send(buffer);}catch(error){console.error('Speech request failed',error?.message||error);return res.status(502).json({ok:false,error:'speech_unreachable'});}});

function hasWebSearch(body){const output=Array.isArray(body?.output)?body.output:[];return output.some(item=>item?.type==='web_search_call');}
function extractOutputText(body){const output=Array.isArray(body?.output)?body.output:[];return output.flatMap(item=>Array.isArray(item?.content)?item.content:[]).filter(part=>part?.type==='output_text'&&typeof part?.text==='string').map(part=>part.text).join('\n').trim();}
app.listen(port,'0.0.0.0',()=>console.log(`SHADOW cloud backend listening on ${port}; model=${model}; image=${imageModel}; tts=${ttsModel}/${ttsVoice}; configured=${Boolean(apiKey)}`));
