package com.shadow.mobile;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.BitmapFactory;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.media.MediaPlayer;
import android.net.Uri;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.provider.Settings;
import android.view.*;
import android.view.inputmethod.EditorInfo;
import android.widget.*;
import android.speech.tts.TextToSpeech;
import android.speech.tts.UtteranceProgressListener;
import java.io.*;
import java.util.*;

/** MOD-73: unified Shadow agent surface with online-first tool execution and verification. */
public class JarvisMainActivity extends Activity implements TextToSpeech.OnInitListener {
    private static final int MIC=801,FILE=802,CAMERA=803;
    private final int BG=Color.rgb(13,14,17),SURFACE=Color.rgb(29,31,36),SURFACE2=Color.rgb(42,44,51),TEXT=Color.rgb(241,243,246),MUTED=Color.rgb(155,160,170);
    private ShadowCore core; private ShadowCloudClient cloud; private ShadowGithubAuth githubAuth; private ShadowVoiceRecognizer voice; private ShadowVoiceIdentityGateway identity; private ShadowRemoteController remotes; private ShadowVoiceStateMachine voiceState; private LinearLayout messages; private EditText input; private ShadowStatusView status; private TextView liveVoice; private TextView micButton; private TextToSpeech tts; private MediaPlayer player; private boolean conversation=true, cloudOnline;
    private boolean voiceOutput=true;
    private boolean handsFreeVoice=true;
    private boolean voiceTurnActive=false;
    private final Handler voiceHandler=new Handler(Looper.getMainLooper());
    private ShadowBargeInMonitor bargeInMonitor;
    private static final String WAKE_PREFS="shadow_voice_prefs";
    private static final String WAKE_ENABLED="wake_enabled";
    private int dp(float n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
    private GradientDrawable bg(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
    private TextView tv(String s,float z){TextView v=new TextView(this);v.setText(s);v.setTextColor(TEXT);v.setTextSize(z);return v;}
    private void stage(String s){if(status!=null)status.setText(ShadowProcessIndicators.render(s));}
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);core=new ShadowCore(this);cloud=new ShadowCloudClient(this);githubAuth=new ShadowGithubAuth(this);identity=new ShadowVoiceIdentityGateway(this);remotes=new ShadowRemoteController(this);
        voiceState=new ShadowVoiceStateMachine(handsFreeVoice,new ShadowVoiceStateMachine.Callback(){
            public void onListening(){runOnUiThread(()->{ShadowWakeWordService.pauseListening();stage("listening");if(liveVoice!=null){liveVoice.setVisibility(View.VISIBLE);if(liveVoice.getText().toString().isEmpty())liveVoice.setText("🎙 Listening…");}if(handsFreeVoice&&!voiceTurnActive){voiceTurnActive=true;}if(handsFreeVoice&&!voice.isActive())voiceHandler.postDelayed(()->{if(handsFreeVoice&&!isFinishing()&&!voice.isActive())listen();},250);});}
            public void onProcessing(){runOnUiThread(()->{stage("thinking");if(liveVoice!=null){liveVoice.setVisibility(View.VISIBLE);liveVoice.setText("⏳ Processing…");}});}
            public void onBotSpeaking(){runOnUiThread(()->{stage("speaking");if(liveVoice!=null){liveVoice.setVisibility(View.VISIBLE);liveVoice.setText("🔊 SHADOW speaking…");}});}
            public void onIdle(){runOnUiThread(()->{stage("done");voiceTurnActive=false;stopBargeInMonitor();ShadowWakeWordService.resumeListening();if(liveVoice!=null){liveVoice.setText("");liveVoice.setVisibility(View.GONE);}});}
            public void stopTtsPlayback(){stopCurrentTts();stopBargeInMonitor();}
        });
        voice=new ShadowVoiceRecognizer(this,new ShadowVoiceRecognizer.Listener(){
            public void onListening(){runOnUiThread(()->stage("listening"));}
            public void onReady(){runOnUiThread(()->{voiceTurnActive=true;voiceState.userStartedListening();});}
            public void onBeginningOfSpeech(){voiceState.speechStarted();}
            public void onPartial(String t){runOnUiThread(()->showLiveVoice(t));}
            public void onText(String t){runOnUiThread(()->handleVoiceText(t));}
            public void onFinal(String t){runOnUiThread(()->handleVoiceText(t));}
            public void onEndOfSpeech(){voiceState.speechEnded();}
            public void onAudioLevel(float level){runOnUiThread(()->{if(liveVoice!=null&&liveVoice.getVisibility()==View.VISIBLE&&voiceState.getState()==ShadowVoiceStateMachine.State.LISTENING){liveVoice.setAlpha(.65f+.35f*level);}});}
            public void onError(String m){runOnUiThread(()->{system(m);if(voiceState!=null)voiceState.userStoppedListening();});}
        });
        tts=new TextToSpeech(this,this);if(isWakeEnabled())try{ShadowWakeWordService.start(this);}catch(Exception ignored){}bargeInMonitor=new ShadowBargeInMonitor(this,new ShadowBargeInMonitor.Listener(){public void onSpeechDetected(){runOnUiThread(()->{if(voiceState!=null&&voiceState.getState()==ShadowVoiceStateMachine.State.BOT_SPEAKING){voiceState.speechStarted();}});}public void onLevel(float level){runOnUiThread(()->{if(liveVoice!=null&&voiceState!=null&&voiceState.getState()==ShadowVoiceStateMachine.State.BOT_SPEAKING){liveVoice.setAlpha(.55f+.45f*level);}});}});ui();check();}
    private void ui(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setPadding(dp(8),dp(4),dp(8),dp(5));
        LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.setPadding(dp(4),dp(4),dp(4),dp(4));TextView menu=tv("☰",24);menu.setGravity(Gravity.CENTER);head.addView(menu,new LinearLayout.LayoutParams(dp(48),dp(52)));ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.shadow_logo);logo.setPadding(dp(8),dp(8),dp(8),dp(8));head.addView(logo,new LinearLayout.LayoutParams(dp(50),dp(52)));LinearLayout tb=new LinearLayout(this);tb.setOrientation(LinearLayout.VERTICAL);tb.setGravity(Gravity.CENTER);TextView title=tv("SHADOW",18);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);tb.addView(title);status=new ShadowStatusView(this);status.setTextColor(Color.rgb(112,210,160));status.setTextSize(11);status.setGravity(Gravity.CENTER);stage("thinking");tb.addView(status);head.addView(tb,new LinearLayout.LayoutParams(0,dp(52),1));TextView more=tv("⋮",26);more.setGravity(Gravity.CENTER);head.addView(more,new LinearLayout.LayoutParams(dp(48),dp(52)));root.addView(head);
        ScrollView sc=new ScrollView(this);sc.setFillViewport(true);messages=new LinearLayout(this);messages.setOrientation(LinearLayout.VERTICAL);messages.setPadding(dp(12),dp(10),dp(12),dp(18));sc.addView(messages);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));assistant("أهلاً محمد 👋\nأنا SHADOW — Z.\nأونلاين هو الوضع الأساسي: AI / Web / Images.\nالصوت والنص شغالين مع بعض — الكلام بيظهر على الشاشة وSHADOW يرد صوتيًا.");
        liveVoice=tv("",11);liveVoice.setTextColor(MUTED);liveVoice.setPadding(dp(8),0,dp(8),dp(2));liveVoice.setVisibility(View.GONE);root.addView(liveVoice,new LinearLayout.LayoutParams(-1,dp(24)));
        LinearLayout wrap=new LinearLayout(this);wrap.setGravity(Gravity.CENTER_VERTICAL);wrap.setPadding(dp(5),dp(3),dp(5),dp(3));wrap.setBackground(bg(SURFACE,24));TextView plus=tv("＋",25);plus.setGravity(Gravity.CENTER);wrap.addView(plus,new LinearLayout.LayoutParams(dp(48),dp(56)));input=new EditText(this);input.setHint("Message SHADOW");input.setHintTextColor(MUTED);input.setTextColor(TEXT);input.setTextSize(16);input.setMaxLines(5);input.setSingleLine(false);input.setBackgroundColor(Color.TRANSPARENT);wrap.addView(input,new LinearLayout.LayoutParams(0,dp(56),1));micButton=tv(handsFreeVoice?"🎙":"🎙",24);micButton.setGravity(Gravity.CENTER);wrap.addView(micButton,new LinearLayout.LayoutParams(dp(52),dp(56)));TextView send=tv("➤",23);send.setGravity(Gravity.CENTER);wrap.addView(send,new LinearLayout.LayoutParams(dp(52),dp(56)));root.addView(wrap,new LinearLayout.LayoutParams(-1,dp(64)));TextView hint=tv("＋ Files/Photos/Camera  •  🎙 Voice input  •  Hands‑Free via menu  •  Web Search  •  GitHub Authorization",10);hint.setTextColor(MUTED);hint.setGravity(Gravity.CENTER);root.addView(hint,new LinearLayout.LayoutParams(-1,dp(24)));setContentView(root);
        menu.setOnClickListener(v->attach());more.setOnClickListener(v->features());plus.setOnClickListener(v->attach());micButton.setOnClickListener(v->listen());send.setOnClickListener(v->send());input.setOnEditorActionListener((v,a,e)->{if(a==EditorInfo.IME_ACTION_SEND){send();return true;}return false;});}
    private void user(String s){TextView v=tv(s,16);v.setPadding(dp(14),dp(9),dp(14),dp(9));v.setBackground(bg(SURFACE2,18));messages.addView(v);bottom();}
    private TextView action(String label){TextView v=tv(label,17);v.setGravity(Gravity.CENTER);v.setTextColor(MUTED);v.setPadding(dp(8),0,dp(8),0);v.setMinWidth(dp(38));v.setMinHeight(dp(38));return v;}
    private void assistant(String s){LinearLayout block=new LinearLayout(this);block.setOrientation(LinearLayout.VERTICAL);block.setPadding(0,dp(3),0,dp(3));TextView v=tv(s,16);v.setPadding(0,dp(8),dp(18),dp(5));v.setAutoLinkMask(android.text.util.Linkify.WEB_URLS);block.addView(v,new LinearLayout.LayoutParams(-1,-2));LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);bar.setPadding(0,0,0,dp(2));TextView copy=action("⧉"),like=action("👍"),dislike=action("👎"),read=action("🔊"),share=action("↗"),more=action("⋮");bar.addView(copy);bar.addView(like);bar.addView(dislike);bar.addView(read);bar.addView(share);bar.addView(more);copy.setOnClickListener(x->copyText(s));like.setOnClickListener(x->{like.setTextColor(Color.rgb(112,210,160));Toast.makeText(this,"تم تسجيل الإعجاب",Toast.LENGTH_SHORT).show();});dislike.setOnClickListener(x->{dislike.setTextColor(Color.rgb(230,120,120));Toast.makeText(this,"تم تسجيل عدم الإعجاب",Toast.LENGTH_SHORT).show();});read.setOnClickListener(x->speakNow(s));share.setOnClickListener(x->shareText(s));more.setOnClickListener(x->assistantMenu(s));block.addView(bar,new LinearLayout.LayoutParams(-1,dp(42)));messages.addView(block);bottom();}
    private void copyText(String s){try{ClipboardManager cm=(ClipboardManager)getSystemService(CLIPBOARD_SERVICE);cm.setPrimaryClip(ClipData.newPlainText("SHADOW",s));Toast.makeText(this,"اتنسخ للحافظة",Toast.LENGTH_SHORT).show();}catch(Exception e){system("مش قادر أنسخ الرسالة.");}}
    private void shareText(String s){try{Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,s);startActivity(Intent.createChooser(i,"مشاركة رد SHADOW"));}catch(Exception e){system("المشاركة غير متاحة دلوقتي.");}}
    private void speakNow(String s){if(cloudOnline){boolean old=voiceOutput;voiceOutput=true;speak(s);voiceOutput=old;}else localSpeak(s);}
    private void assistantMenu(String s){PopupMenu p=new PopupMenu(this,findViewById(android.R.id.content));p.getMenu().add("⧉ نسخ");p.getMenu().add("↗ مشاركة");p.getMenu().add("🔊 قراءة بصوت");p.getMenu().add("⏹ إيقاف الصوت");p.setOnMenuItemClickListener(i->{String n=i.getTitle().toString();if(n.contains("نسخ"))copyText(s);else if(n.contains("مشاركة"))shareText(s);else if(n.contains("قراءة"))speakNow(s);else {stopCurrentTts();voiceState.userStoppedListening();}return true;});p.show();}
    private void system(String s){TextView v=tv(s,11);v.setTextColor(MUTED);messages.addView(v);bottom();}
    private void bottom(){messages.post(()->{ViewParent p=messages.getParent();if(p instanceof ScrollView)((ScrollView)p).fullScroll(View.FOCUS_DOWN);});}
    private void check(){new Thread(()->{cloudOnline=cloud.health();runOnUiThread(()->stage(cloudOnline?"online":"reconnecting"));}).start();}
    private boolean handleIdentityCommand(String s){String x=s.trim().toLowerCase(Locale.ROOT);if(x.contains("حالة الهوية")||x.contains("حاله الهويه")||x.equals("identity status")||x.equals("voice identity status")){assistant(identity.status());return true;}if(x.contains("اقفل الهوية")||x.contains("اقفل الهويه")||x.equals("lock identity")||x.equals("logout shadow")){identity.lock();assistant("تم قفل هوية الـMaster. الأوامر الحساسة هتحتاج كلمة السر تاني.");return true;}if(x.startsWith("عيّن كلمة السر:")||x.startsWith("عين كلمة السر:")||x.startsWith("عيّن كلمه السر:")||x.startsWith("عين كلمه السر:")||x.startsWith("set passphrase:")||x.startsWith("set password:")){String p=identity.extractPassphrase(s);if(identity.enroll(p)){assistant("تم تسجيل كلمة سر الـMaster محليًا بشكل آمن. مش هخزن الكلمة نفسها، فقط SHA-256.\nقول: كلمة السر: <الكلمة> عند طلب أمر حساس.");}else assistant("كلمة السر لازم تكون 6 أحرف/رموز على الأقل.");return true;}return false;}
    private boolean authorizeSensitive(String s){if(!identity.isSensitiveCommand(s)||identity.isAuthenticated())return true;String phrase=identity.extractPassphrase(s);if(!phrase.isEmpty()&&identity.authenticate(phrase)){system("SHADOW • Master identity authenticated for this session ✓");return true;}assistant("الأمر ده حساس وعايز تأكيد هوية الـMaster.\nلو كلمة السر متسجلة، ابعتها بالشكل: كلمة السر: <الكلمة>\nأو استخدم: عيّن كلمة السر: <كلمة جديدة>");return false;}
    private boolean handleOutputCommand(String s){String x=s.trim().toLowerCase(Locale.ROOT);if(x.equals("رد كتابة")||x.equals("رد كتابه")||x.equals("من غير صوت")||x.equals("بدون صوت")||x.equals("text only")||x.equals("text response")){voiceOutput=false;assistant("تم — هرد كتابة فقط من دلوقتي.");stage("done");return true;}if(x.equals("رد صوتي")||x.equals("شغل الصوت")||x.equals("شغّل الصوت")||x.equals("voice on")||x.equals("voice response")){voiceOutput=true;assistant("تم — الصوت اتفعّل.");speak("تم — الصوت اتفعّل.");stage("done");return true;}return false;}
    private boolean isGithubCommand(String s){String x=s.trim().toLowerCase(Locale.ROOT);boolean github=x.contains("github")||x.contains("git hub")||x.contains("جيت هاب")||x.contains("جيتهاب")||x.contains("github.com")||x.contains("meslammo/shadow");if(!github)return false;return x.contains("authorization")||x.contains("authorize")||x.contains("auth")||x.contains("اربط")||x.contains("ابدأ")||x.contains("ابدء")||x.contains("connect")||x.contains("ربط")||x.contains("حالة")||x.contains("status")||x.contains("افصل")||x.contains("disconnect")||x.contains("تطوير")||x.contains("عدل")||x.contains("عدّل")||x.contains("نفذ")||x.contains("نفّذ")||x.contains("development")||x.contains("develop")||x.contains("repo")||x.contains("repository")||x.contains("فرع")||x.contains("branch");}
    private void handleGithubCommand(String s){String x=s.trim().toLowerCase(Locale.ROOT);if(x.contains("حالة")||x.equals("github status")){assistant(githubAuth.isConnected()?"GitHub متوصل بالفعل ومفتاح التفويض محفوظ بشكل مشفّر على الجهاز.":"GitHub مش متوصل. قول: اربط جيت هاب.");return;}if(x.contains("افصل")||x.contains("disconnect github")){githubAuth.disconnect();assistant("تم فصل GitHub من Shadow.");return;}connectGithub();}
    private void connectGithub(){stage("authenticating");system("SHADOW • GitHub intent detected — Chat route blocked. بيجهّز تفويض GitHub…");new Thread(()->{try{ShadowCloudClient.GithubDevice d=cloud.startGithubDevice();runOnUiThread(()->{try{String uri=d.verificationUriComplete.isEmpty()?d.verificationUri:d.verificationUriComplete;startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse(uri)));}catch(Exception ignored){}new AlertDialog.Builder(this).setTitle("ربط GitHub بـ SHADOW").setMessage("افتح GitHub ووافق على التفويض.\n\nالكود: "+d.userCode+"\n\nبعد الموافقة اضغط تم.").setPositiveButton("تم",(dialog,which)->pollGithub(d)).setNegativeButton("إلغاء",(dialog,which)->stage("online")).show();});}catch(Exception e){runOnUiThread(()->{assistant("GitHub route وصل للـAuthorization لكن التفويض نفسه غير متاح: "+e.getMessage());stage("online");});}}).start();}
    private void pollGithub(ShadowCloudClient.GithubDevice d){stage("authenticating");new Thread(()->{try{long deadline=System.currentTimeMillis()+Math.max(60_000L,d.expiresIn*1000L);int wait=Math.max(2,d.interval);while(System.currentTimeMillis()<deadline){ShadowCloudClient.GithubPoll p=cloud.pollGithubDevice(d.deviceCode);if("authorized".equals(p.status)){githubAuth.saveToken(p.accessToken);runOnUiThread(()->{assistant("تم ربط GitHub بـ SHADOW ✓\nالتفويض محفوظ على الجهاز بشكل مشفّر.\nدلوقتي Shadow يقدر يستخدم صلاحية GitHub اللي وافقت عليها لتنفيذ مهام التطوير بعد التأكيد.");stage("online");});return;}if("denied".equals(p.status)||"expired".equals(p.status)||"error".equals(p.status)){String msg="expired".equals(p.status)?"انتهى كود التفويض.":"denied".equals(p.status)?"تم رفض تفويض GitHub.":"تفويض GitHub فشل.";runOnUiThread(()->{assistant(msg);stage("online");});return;}Thread.sleep(wait*1000L);if("slow_down".equals(p.status))wait+=5;}runOnUiThread(()->{assistant("انتهى وقت انتظار تفويض GitHub. جرّب: اربط جيت هاب.");stage("online");});}catch(Exception e){runOnUiThread(()->{assistant("حصل خطأ أثناء ربط GitHub: "+e.getMessage());stage("online");});}}).start();}
    private void handlePendingAction(String original, ShadowCloudClient.CloudReply reply){final ShadowCloudClient.PendingAction pa=reply.pendingAction;if(pa==null)return;final String command=(pa.action+" "+pa.argument).trim();Runnable execute=()->{stage("executing");String result;try{result=ShadowDeviceExecution.execute(this,command);}catch(Throwable e){result="تعذر التنفيذ: "+e.getClass().getSimpleName();}final String verified=(result==null||result.trim().isEmpty())?"لم يرجع الجهاز نتيجة مؤكدة لتنفيذ الإجراء.":result;stage("verifying");new Thread(()->{try{ShadowCloudClient.CloudReply next=cloud.continueAgent(reply.provider,reply.responseId,pa.toolCallId,original,verified);runOnUiThread(()->{assistant(next.answer.isEmpty()?verified:next.answer);if(!next.answer.isEmpty())speak(next.answer);stage(next.offline?"reconnecting":"online");if(next.pendingAction!=null)handlePendingAction(original,next);});}catch(Exception e){runOnUiThread(()->{assistant(verified);if(!verified.isEmpty())speak(verified);stage("online");});}}).start();};
        if(pa.requiresConfirmation)runOnUiThread(()->new AlertDialog.Builder(this).setTitle("تأكيد تنفيذ الإجراء").setMessage(pa.reason.isEmpty()?command:pa.reason+"\n\n"+command).setPositiveButton("تنفيذ",(d,w)->execute.run()).setNegativeButton("إلغاء",(d,w)->{assistant("تم إلغاء الإجراء.");stage("online");}).show());else runOnUiThread(execute);
    }
    private void send(){String s=input.getText().toString().trim();if(s.isEmpty())return;user(s);input.setText("");if(handleIdentityCommand(s))return;if(!authorizeSensitive(s))return;if(handleOutputCommand(s))return;if(isGithubCommand(s)){handleGithubCommand(s);return;}stage("thinking");
        if(isImage(s)){stage("designing");generateImage(s);return;}
        stage("online");new Thread(()->{try{ShadowCloudClient.CloudReply r=cloud.chat(s);cloudOnline=true;runOnUiThread(()->{stage("analyzing");if(r.pendingAction!=null){if(!r.answer.isEmpty())assistant(r.answer);handlePendingAction(s,r);return;}assistant(r.answer);speak(r.answer);stage(r.offline?"reconnecting":"online");});}catch(Throwable cloudError){cloudOnline=false;String local=null;try{local=ShadowPhoneController.execute(this,s);}catch(Throwable ignored){}if(local==null||local.trim().isEmpty())try{local=core.handle(s);}catch(Throwable ignored){}if(local==null||local.trim().isEmpty())try{local=core.offlineChat(s);}catch(Throwable ignored){}final String answer=(local==null||local.trim().isEmpty())?"الأونلاين مش متاح دلوقتي، ومفيش تنفيذ محلي مناسب للأمر.":local;runOnUiThread(()->{assistant(answer);stage("reconnecting");speak(answer);});}}).start();}
    private boolean isImage(String s){String x=s.toLowerCase(Locale.ROOT);return x.contains("صمم صورة")||x.contains("اعمل صورة")||x.contains("صورة لـ")||x.contains("generate image")||x.contains("create an image")||x.contains("design an image");}
    private void generateImage(String prompt){system("SHADOW • بيصمم الصورة أونلاين…");new Thread(()->{try{String b64=cloud.generateImage(prompt);byte[] data=android.util.Base64.decode(b64,android.util.Base64.DEFAULT);runOnUiThread(()->{ImageView image=new ImageView(this);image.setAdjustViewBounds(true);image.setScaleType(ImageView.ScaleType.CENTER_CROP);image.setImageBitmap(BitmapFactory.decodeStream(new ByteArrayInputStream(data)));messages.addView(image,new LinearLayout.LayoutParams(-1,dp(320)));assistant("اتفضل — الصورة جاهزة.");stage("online");});}catch(Throwable e){runOnUiThread(()->{assistant("مش قادر أولّد الصورة دلوقتي: "+e.getMessage());stage("reconnecting");});}}).start();}
    private void attach(){PopupMenu p=new PopupMenu(this,findViewById(android.R.id.content));p.getMenu().add("Files");p.getMenu().add("Photos");p.getMenu().add("Camera");p.setOnMenuItemClickListener(i->{String n=i.getTitle().toString();if(n.equals("Files")){Intent x=new Intent(Intent.ACTION_OPEN_DOCUMENT);x.addCategory(Intent.CATEGORY_OPENABLE);x.setType("*/*");startActivityForResult(x,FILE);}else if(n.equals("Photos")){Intent x=new Intent(Intent.ACTION_PICK);x.setType("image/*");startActivityForResult(x,FILE);}else{try{startActivityForResult(new Intent(android.provider.MediaStore.ACTION_IMAGE_CAPTURE),CAMERA);}catch(Exception e){system("No camera application is available.");}}return true;});p.show();}
    private void features(){PopupMenu p=new PopupMenu(this,findViewById(android.R.id.content));String[] a={"📺 TV Remote","❄️ AC Remote","🔎 Remote capabilities","🌐 Web search","🎨 Image design","📱 Deep phone control","🧠 Development Agent","🔐 GitHub Authorization","🎙 Hands-Free: "+(handsFreeVoice?"ON":"OFF"),"🌙 Wake Word: "+(isWakeEnabled()?"ON":"OFF"),"Profile / Memory","System status","🔒 Lock Master identity","Settings"};for(String s:a)p.getMenu().add(s);p.setOnMenuItemClickListener(i->{String n=i.getTitle().toString();if(n.startsWith("📺")||n.startsWith("❄️")||n.startsWith("🔎"))remotes.showCenter();else if(n.startsWith("📱"))startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS));else if(n.startsWith("🌐")){input.setText("ابحث أونلاين عن ");input.requestFocus();}else if(n.startsWith("🎨")){input.setText("صمم صورة: ");input.requestFocus();}else if(n.startsWith("🧠"))system("Development Agent: analyze → plan → approve → edit → test → report");else if(n.startsWith("🔐 GitHub"))connectGithub();else if(n.startsWith("🎙 Hands-Free")){handsFreeVoice=!handsFreeVoice;voiceState.setHandsFree(handsFreeVoice);assistant(handsFreeVoice?"Hands‑Free اتفعل — بعد كل رد صوتي Shadow هيبدأ يسمع تاني تلقائيًا.":"Hands‑Free اتقفل — الصوت هيفضل بنقرة واحدة فقط.");}
        else if(n.startsWith("🌙 Wake Word")){toggleWakeWord();}else if(n.equals("System status"))assistant(core.handle("status"));else if(n.startsWith("🔒")){identity.lock();assistant("تم قفل هوية الـMaster.");}else if(n.equals("Settings"))startActivity(new Intent(Settings.ACTION_SETTINGS));return true;});p.show();}
    private boolean isWakeEnabled(){return getSharedPreferences(WAKE_PREFS,MODE_PRIVATE).getBoolean(WAKE_ENABLED,false);}
    private void toggleWakeWord(){
        boolean next=!isWakeEnabled();
        getSharedPreferences(WAKE_PREFS,MODE_PRIVATE).edit().putBoolean(WAKE_ENABLED,next).apply();
        if(next){try{ShadowWakeWordService.start(this);assistant("Wake Word اتفعل. SHADOW دلوقتي شغال في الخلفية على الجهاز، وبيستخدم ميكروفون مع إشعار نظام.");}catch(Throwable t){assistant("مش قادر أشغل Wake Word حالياً: "+t.getMessage());}}
        else {ShadowWakeWordService.stop(this);assistant("Wake Word اتقفل.");}
    }
    private void listen(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},MIC);return;}voiceTurnActive=true;stage("listening");if(liveVoice!=null){liveVoice.setVisibility(View.VISIBLE);liveVoice.setText("🎙 Listening…");}voice.start("ar-EG");}
    private void showLiveVoice(String text){if(liveVoice==null)return;liveVoice.setVisibility(View.VISIBLE);liveVoice.setAlpha(1f);liveVoice.setText("🎙 "+text);}
    private void handleVoiceText(String text){String s=text==null?"":text.trim();if(s.isEmpty())return;if(liveVoice!=null){liveVoice.setText("");liveVoice.setVisibility(View.GONE);}input.setText(s);send();}
    private void stopCurrentTts(){try{if(tts!=null)tts.stop();}catch(Exception ignored){}try{if(player!=null){player.stop();player.release();player=null;}}catch(Exception ignored){}}
    private void startBargeInMonitor(){if(bargeInMonitor!=null&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED)bargeInMonitor.start();}
    private void stopBargeInMonitor(){if(bargeInMonitor!=null)bargeInMonitor.stop();}

    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result==RESULT_OK&&data!=null)system("Attached: "+(data.getData()!=null?String.valueOf(data.getData().getLastPathSegment()):"camera capture"));}
    private boolean arabic(String s){for(int i=0;i<s.length();i++){char c=s.charAt(i);if(c>=0x0600&&c<=0x06FF)return true;}return false;}
    private void speak(String s){if(s==null||s.trim().isEmpty())return;if(!voiceOutput){if(voiceTurnActive&&voiceState!=null)voiceState.responseFinishedWithoutTts();return;}if(voiceState!=null)voiceState.ttsStarted();if(cloudOnline)new Thread(()->{try{byte[] audio=cloud.synthesizeSpeech(s);File f=new File(getCacheDir(),"shadow_voice.mp3");try(FileOutputStream o=new FileOutputStream(f)){o.write(audio);}runOnUiThread(()->play(f));}catch(Exception e){runOnUiThread(()->localSpeak(s));}}).start();else localSpeak(s);}
    private void play(File f){try{if(player!=null)player.release();player=new MediaPlayer();player.setDataSource(f.getAbsolutePath());player.setOnCompletionListener(m->{m.release();player=null;stopBargeInMonitor();if(voiceState!=null)voiceState.ttsFinished();});player.setOnErrorListener((m,what,extra)->{try{m.release();}catch(Exception ignored){}player=null;stopBargeInMonitor();if(voiceState!=null)voiceState.ttsFinished();return true;});player.setOnPreparedListener(m->{m.start();startBargeInMonitor();});player.prepare();}catch(Exception e){localSpeak("حصلت مشكلة في الصوت.");}}
    private void localSpeak(String s){if(tts==null||!voiceOutput){if(voiceState!=null)voiceState.responseFinishedWithoutTts();return;}try{tts.setLanguage(arabic(s)?new Locale("ar","EG"):Locale.US);tts.setPitch(.72f);tts.setSpeechRate(.96f);tts.speak(s,TextToSpeech.QUEUE_FLUSH,null,"shadow");}catch(Exception ignored){if(voiceState!=null)voiceState.ttsFinished();}}
    @Override public void onInit(int c){if(tts!=null){tts.setLanguage(new Locale("ar","EG"));tts.setPitch(.72f);tts.setSpeechRate(.96f);tts.setOnUtteranceProgressListener(new UtteranceProgressListener(){@Override public void onStart(String id){startBargeInMonitor();}@Override public void onDone(String id){stopBargeInMonitor();{runOnUiThread(()->{if(voiceState!=null)voiceState.ttsFinished();});}@Override public void onError(String id){runOnUiThread(()->{if(voiceState!=null)voiceState.ttsFinished();});}});}}
    @Override protected void onDestroy(){handsFreeVoice=false;voiceHandler.removeCallbacksAndMessages(null);if(voiceState!=null)voiceState.setHandsFree(false);stopBargeInMonitor();if(bargeInMonitor!=null)bargeInMonitor.destroy();if(voice!=null)voice.destroy();stopCurrentTts();if(tts!=null)tts.shutdown();super.onDestroy();}
}
