package com.shadow.mobile;
import android.Manifest;import android.content.*;import android.content.pm.PackageManager;import android.app.AlertDialog;import android.view.*;import android.widget.*;import java.util.*;
/** MOD-69.2: preserve development/radar bridge on top of the current master UI/runtime. */
public class JarvisMainActivityV4 extends JarvisMainActivity {
 private ShadowDevelopmentAgent development;
 @Override public void onCreate(android.os.Bundle b){super.onCreate(b);development=new ShadowDevelopmentAgent(this);ViewGroup root=findViewById(android.R.id.content);if(root==null)return;TextView send=findText(root,"➤");if(send!=null)send.setOnTouchListener((v,e)->{if(e.getAction()==MotionEvent.ACTION_UP){EditText in=findInput(root);if(in!=null){String s=in.getText().toString().trim();if(isDevelopment(s)){runDevelopment(s);return true;}if(isRadar(s)){startShadowRadar();return true;}}}return false;});}
 private TextView findText(ViewGroup g,String t){for(int i=0;i<g.getChildCount();i++){View v=g.getChildAt(i);if(v instanceof TextView&&t.contentEquals(((TextView)v).getText()))return(TextView)v;if(v instanceof ViewGroup){TextView r=findText((ViewGroup)v,t);if(r!=null)return r;}}return null;}
 private EditText findInput(ViewGroup g){for(int i=0;i<g.getChildCount();i++){View v=g.getChildAt(i);if(v instanceof EditText)return(EditText)v;if(v instanceof ViewGroup){EditText r=findInput((ViewGroup)v);if(r!=null)return r;}}return null;}
 private boolean isRadar(String x){String s=x.toLowerCase(Locale.ROOT);return s.contains("شغل الرادار")||s.contains("شغّل الرادار")||s.contains("رادار شادو")||s.contains("كاميرات الطريق")||s.contains("كاميرات السرعة");}
 private boolean isDevelopment(String x){String s=x.toLowerCase(Locale.ROOT);return s.contains("طور شادو")||s.contains("طوّر شادو")||s.contains("طور نفسك")||s.contains("طوّر نفسك")||s.contains("كمل شادو")||s.contains("كمّل شادو")||s.contains("حلل المشروع")||s.contains("حلّل المشروع")||s.contains("شوف الناقص")||s.contains("development engine")||s.contains("development agent")||s.contains("self development");}
 private void runDevelopment(String request){development.plan(request);Toast.makeText(this,"🧠 Development Engine بدأ: تحليل → بحث → تقييم → خطة → اختبار → Build → Verify",Toast.LENGTH_LONG).show();new AlertDialog.Builder(this).setTitle("🧠 SHADOW Development Engine").setMessage("Quest اتفتح للتطوير.\n\n"+development.status()+"\n\nالخطوة التالية: تحليل المشروع وتحديد النواقص.\nالتعديل الفعلي على GitHub لا يتم الادعاء به إلا بعد تنفيذ موثّق.").setPositiveButton("تمام",null).show();}
 private void startShadowRadar(){if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION},904);return;}Intent i=new Intent(this,ShadowRadarService.class);if(android.os.Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);Toast.makeText(this,"SHADOW Radar شغال في الخلفية — مستقل عن Radarbot.",Toast.LENGTH_LONG).show();}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==904&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)startShadowRadar();}
}
