package com.shadow.mobile;
import android.app.*;import android.content.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.view.*;import android.widget.*;import java.util.*;
/** MOD-40/41: overlays Quest/Build and compact attachment chooser without replacing stable V2. */
public final class JarvisMainActivityV3 extends JarvisMainActivityV2 {
 private ShadowDevelopmentAgent dev;private ShadowWorkspace workspace;private int dp(float n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}private GradientDrawable bg(){GradientDrawable g=new GradientDrawable();g.setColor(Color.rgb(29,31,36));g.setCornerRadius(dp(18));return g;}
 @Override protected void onCreate(android.os.Bundle b){super.onCreate(b);dev=new ShadowDevelopmentAgent(this);workspace=new ShadowWorkspace(this);ViewGroup content=findViewById(android.R.id.content);if(content.getChildCount()==0)return;View root0=content.getChildAt(0);if(!(root0 instanceof ViewGroup))return;ViewGroup root=(ViewGroup)root0;LinearLayout q=new LinearLayout(this);q.setGravity(Gravity.CENTER);q.setPadding(dp(12),0,dp(12),dp(4));TextView quest=button("QUEST"),build=button("BUILD");q.addView(quest,new LinearLayout.LayoutParams(dp(92),dp(34)));q.addView(new Space(this),new LinearLayout.LayoutParams(dp(12),1));q.addView(build,new LinearLayout.LayoutParams(dp(92),dp(34)));root.addView(q,Math.min(1,root.getChildCount()));quest.setOnClickListener(v->questDialog());build.setOnClickListener(v->buildDialog());TextView plus=findText(root,"＋");if(plus!=null)plus.setOnClickListener(v->compactAttachments());TextView send=findText(root,"➤");if(send!=null)send.setOnTouchListener((v,e)->{if(e.getAction()==MotionEvent.ACTION_UP){EditText in=findInput(root);if(in!=null&&handleSpecial(in.getText().toString().trim()))return true;}return false;});}
 private TextView button(String s){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(12);v.setGravity(Gravity.CENTER);v.setBackground(bg());return v;}private TextView findText(ViewGroup g,String t){for(int i=0;i<g.getChildCount();i++){View v=g.getChildAt(i);if(v instanceof TextView&&t.contentEquals(((TextView)v).getText()))return(TextView)v;if(v instanceof ViewGroup){TextView r=findText((ViewGroup)v,t);if(r!=null)return r;}}return null;}private EditText findInput(ViewGroup g){for(int i=0;i<g.getChildCount();i++){View v=g.getChildAt(i);if(v instanceof EditText)return(EditText)v;if(v instanceof ViewGroup){EditText r=findInput((ViewGroup)v);if(r!=null)return r;}}return null;}
 private boolean handleSpecial(String s){String x=s.toLowerCase(Locale.ROOT);if(x.contains("كمل شادو")||x.contains("حلل المشروع")||x.contains("development agent")||x.contains("ضيف ملف")||x.contains("اضف ملف")){Toast.makeText(this,dev.plan(s),Toast.LENGTH_LONG).show();return true;}if(x.contains("وافق ونفذ")||x.contains("وافق ونفّذ")||x.contains("نفذ الخطة")){Toast.makeText(this,dev.approve(),Toast.LENGTH_LONG).show();return true;}if(x.contains("شغل الرادار")||x.contains("شغّل الرادار")||x.contains("رادار شادو")||x.contains("كاميرات الطريق")||x.contains("كاميرات السرعة")){if(android.os.Build.VERSION.SDK_INT>=23&&checkSelfPermission("android.permission.ACCESS_FINE_LOCATION")!=0){requestPermissions(new String[]{"android.permission.ACCESS_FINE_LOCATION"},904);}else startService(new Intent(this,ShadowRadarService.class));Toast.makeText(this,"SHADOW Radar شغال مستقل — مش بيفتح Radarbot.",Toast.LENGTH_LONG).show();return true;}return false;}
 private void questDialog(){new AlertDialog.Builder(this).setTitle("QUEST").setMessage("Development Agent\n\n"+dev.status()+"\n\n"+(dev.state()==ShadowDevelopmentAgent.State.AWAITING_APPROVAL?"الخطة جاهزة للموافقة.":"قول: كمل شادو / حلل المشروع عشان أعمل Quest.")).setPositiveButton("إغلاق",null).show();}
 private void buildDialog(){new AlertDialog.Builder(this).setTitle("BUILD").setMessage("BUILD CONTROL\n\nWorkspace: "+workspace.fileCount()+" files\nAnalyze → Edit → Test → Build → Verify").setPositiveButton("GitHub Actions",(d,w)->startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://github.com/meslammo/ShaDoW/actions")))).setNegativeButton("إغلاق",null).show();}
 private void compactAttachments(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.HORIZONTAL);box.setGravity(Gravity.CENTER);box.setPadding(dp(8),dp(10),dp(8),dp(10));box.setBackground(bg());final PopupWindow[] p=new PopupWindow[1];String[] a={"📄 ملفات","🖼 صور","📷 كاميرا","📦 ZIP"};for(String s:a){TextView b=button(s);box.addView(b,new LinearLayout.LayoutParams(dp(82),dp(58)));b.setOnClickListener(v->{p[0].dismiss();choose(s);});}p[0]=new PopupWindow(box,-2,-2,true);p[0].setBackgroundDrawable(bg());p[0].setOutsideTouchable(true);p[0].setElevation(dp(10));p[0].showAtLocation(findViewById(android.R.id.content),Gravity.BOTTOM|Gravity.CENTER_HORIZONTAL,0,dp(82));}
 private void choose(String s){Intent i;if(s.contains("كاميرا"))i=new Intent(android.provider.MediaStore.ACTION_IMAGE_CAPTURE);else{i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(s.contains("صور")?"image/*":"*/*");}try{startActivityForResult(i,902);}catch(Exception ignored){}}
}