package com.shadow.mobile;

import android.Manifest;
import android.app.Activity;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.BitmapFactory;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.media.MediaPlayer;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.provider.Settings;
import android.speech.tts.TextToSpeech;
import android.speech.tts.UtteranceProgressListener;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.util.*;

/** MOD-38.2: production Jarvis interaction loop — Egyptian Arabic, male TTS, image routing, voice loop, precise capability responses. */
public class JarvisMainActivityV2 extends Activity implements TextToSpeech.OnInitListener {
    private static final int MIC=901,FILE=902,CAMERA=903;
    private final int BG=Color.rgb(13,14,17),SURFACE=Color.rgb(29,31,36),SURFACE2=Color.rgb(42,44,51),TEXT=Color.rgb(241,243,246),MUTED=Color.rgb(155,160,170);
    private ShadowCore core; private ShadowCloudClient cloud; private ShadowVoiceRecognizer voice; private ShadowRemoteController remotes; private LinearLayout messages; private EditText input; private ShadowStatusView status; private TextToSpeech tts; private MediaPlayer player; private boolean online; private boolean handsFree=true; private final Handler h=new Handler(Looper.getMainLooper());
    private int dp(float n){return(int)(n*getResources().getDisplayMetrics().density+.5f);} private GradientDrawable bg(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;} private TextView tv(String s,float z){TextView v=new TextView(this);v.setText(s);v.setTextColor(TEXT);v.setTextSize(z);return v;} private void stage(String s){if(status!=null)status.setText(ShadowProcessIndicators.render(s));}
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);core=new ShadowCore(this);cloud=new ShadowCloudClient(this);remotes=new ShadowRemoteController(this);voice=new ShadowVoiceRecognizer(this,new ShadowVoiceRecognizer.Listener(){public void onListening(){runOnUiThread(()->stage("listening"));}public void onText(String t){runOnUiThread(()->{input.setText(t);send();});}public void onError(String m){runOnUiThread(()->{system(m);if(handsFree)h.postDelayed(()->listen(),1200);});}});tts=new TextToSpeech(this,this);buildUi();new Thread(()->{online=cloud.health();runOnUiThread(()->stage(online?"done":"thinking"));}).start();}
    private void buildUi(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setPadding(dp(8),dp(4),dp(8),dp(5));LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView menu=tv("☰",24);menu.setGravity(Gravity.CENTER);head.addView(menu,new LinearLayout.LayoutParams(dp(48),dp(52)));ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.shadow_logo);logo.setPadding(dp(8),dp(8),dp(8),dp(8));head.addView(logo,new LinearLayout.LayoutParams(dp(50),dp(52)));LinearLayout titleBox=new LinearLayout(this);titleBox.setOrientation(LinearLayout.VERTICAL);titleBox.setGravity(Gravity.CENTER);TextView title=tv("SHADOW",18);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);titleBox.addView(title);status=new ShadowStatusView(this);status.setTextColor(Color.rgb(112,210,160));status.setTextSize(11);titleBox.addView(status);head.addView(titleBox,new LinearLayout.LayoutParams(0,dp(52),1));TextView more=tv("⋮",26);more.setGravity(Gravity.CENTER);head.addView(more,new LinearLayout.LayoutParams(dp(48),dp(52)));root.addView(head);
        ScrollView sc=new ScrollView(this);messages=new LinearLayout(this);messages.setOrientation(LinearLayout.VERTICAL);messages.setPadding(dp(12),dp(10),dp(12),dp(18));sc.addView(messages);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));assistant("أهلاً يا محمد 👋\nأنا SHADOW — Z.\nكلمني بالمصري عادي. الصوت مصري راجل، والأوامر الصوتية شغالة Hands‑Free.");
        LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(5),dp(3),dp(5),dp(3));bar.setBackground(bg(SURFACE,24));TextView plus=tv("＋",25);plus.setGravity(Gravity.CENTER);bar.addView(plus,new LinearLayout.LayoutParams(dp(48),dp(56)));input=new EditText(this);input.setHint("اكتب لـ SHADOW...");input.setHintTextColor(MUTED);input.setTextColor(TEXT);input.setTextSize(16);input.setMaxLines(5);input.setBackgroundColor(Color.TRANSPARENT);bar.addView(input,new LinearLayout.LayoutParams(0,dp(56),1));TextView mic=tv("🎙",24);mic.setGravity(Gravity.CENTER);bar.addView(mic,new LinearLayout.LayoutParams(dp(52),dp(56)));TextView send=tv("➤",23);send.setGravity(Gravity.CENTER);bar.addView(send,new LinearLayout.LayoutParams(dp(52),dp(56)));root.addView(bar,new LinearLayout.LayoutParams(-1,dp(64)));TextView hint=tv("＋ ملفات/صور/كاميرا  •  🎙 صوت  •  Hands‑Free  •  🌐 بحث",10);hint.setTextColor(MUTED);hint.setGravity(Gravity.CENTER);root.addView(hint,new LinearLayout.LayoutParams(-1,dp(24)));setContentView(root);
        menu.setOnClickListener(v->attach());more.setOnClickListener(v->features());plus.setOnClickListener(v->attach());mic.setOnClickListener(v->{handsFree=true;listen();});send.setOnClickListener(v->send());input.setOnEditorActionListener((v,a,e)->{if(a==android.view.inputmethod.EditorInfo.IME_ACTION_SEND){send();return true;}return false;});stage("thinking");}
    private void user(String s){TextView v=tv(s,16);v.setPadding(dp(14),dp(9),dp(14),dp(9));v.setBackground(bg(SURFACE2,18));messages.addView(v);bottom();} private void assistant(String s){TextView v=tv(s,16);v.setPadding(0,dp(8),dp(18),dp(8));v.setAutoLinkMask(android.text.util.Linkify.WEB_URLS);messages.addView(v);bottom();} private void system(String s){TextView v=tv(s,11);v.setTextColor(MUTED);messages.addView(v);bottom();} private void bottom(){messages.post(()->{ViewParent p=messages.getParent();if(p instanceof ScrollView)((ScrollView)p).fullScroll(View.FOCUS_DOWN);});}
    private void send(){String s=input.getText().toString().trim();if(s.isEmpty())return;user(s);input.setText("");stage("thinking");String cap=capabilityAnswer(s);if(cap!=null){assistant(cap);speak(cap);return;}String local=ShadowPhoneController.execute(this,s);if(local!=null){stage("executing");assistant(local);speak(local);return;}if(isImage(s)){stage("designing");generateImage(s);return;}stage("searching");new Thread(()->{try{ShadowCloudClient.CloudReply r=cloud.chat(s);online=true;runOnUiThread(()->{stage("analyzing");assistant(r.answer);speak(r.answer);});}catch(Throwable e){online=false;String answer="الأونلاين مش متاح دلوقتي، وSHADOW مش هيستخدم إجابة AI أوفلاين بدل الخدمة السحابية.";runOnUiThread(()->{assistant(answer);stage("reconnecting");});}}).start();}
    private String capabilityAnswer(String s){String x=s.toLowerCase(Locale.ROOT);if(x.contains("تحديث نفسك")||x.contains("تعمل تحديث")||x.contains("حدث نفسك")||x.contains("update yourself")||x.contains("self update")||x.contains("تقدر تعمل تحديث")){return "أيوه أقدر أساعد في التحديث، بس فيه فرق مهم: أقدر أحلل المشروع وأطلع خطة وملفات واختبارات، لكن تنفيذ تعديل على GitHub محتاج قناة GitHub مصرح لها بالكتابة. مش هكدب عليك وأقول اتحدثت وأنا ما نفذتش. لما قناة الكتابة تتفعل: تحليل → خطة → موافقة → تعديل → Build → Test → تقرير.";}return null;}
    private boolean isImage(String s){String x=s.toLowerCase(Locale.ROOT);boolean noun=x.contains("صورة")||x.contains("صوره")||x.contains("image")||x.contains("picture")||x.contains("drawing");boolean verb=x.contains("اعمل")||x.contains("اعملي")||x.contains("ارسم")||x.contains("صمم")||x.contains("صمّم")||x.contains("ولد")||x.contains("ولّد")||x.contains("generate")||x.contains("create")||x.contains("design");return (noun&&verb)||x.startsWith("ارسم ")||x.startsWith("صمم ")||x.startsWith("generate ")||x.startsWith("create ");}
    private void generateImage(String prompt){system("SHADOW • بجهز الصورة أونلاين…");new Thread(()->{try{String b64=cloud.generateImage(prompt);byte[] data=android.util.Base64.decode(b64,android.util.Base64.DEFAULT);runOnUiThread(()->{ImageView image=new ImageView(this);image.setAdjustViewBounds(true);image.setScaleType(ImageView.ScaleType.CENTER_CROP);image.setImageBitmap(BitmapFactory.decodeByteArray(data,0,data.length));messages.addView(image,new LinearLayout.LayoutParams(-1,dp(320)));String ok="تمام — الصورة اتعملت.";assistant(ok);speak(ok);stage("done");});}catch(Throwable e){String msg="أداة الصور رجعت خطأ: "+(e.getMessage()==null?"مش معروف":e.getMessage());runOnUiThread(()->{assistant(msg+"\nجرّب نفس الطلب تاني بعد ما نتأكد إن خدمة الصور الأونلاين شغالة.");stage("done");});}}).start();}
    private void speak(String text){if(text==null||text.trim().isEmpty())return;stage("speaking");if(online)new Thread(()->{try{byte[] audio=cloud.synthesizeSpeech(text);File f=new File(getCacheDir(),"shadow_voice.mp3");try(FileOutputStream o=new FileOutputStream(f)){o.write(audio);}runOnUiThread(()->play(f));}catch(Exception e){runOnUiThread(()->localSpeak(text));}}).start();else localSpeak(text);}
    private void play(File f){try{if(player!=null)player.release();player=new MediaPlayer();player.setDataSource(f.getAbsolutePath());player.setOnCompletionListener(m->{m.release();player=null;stage("done");if(handsFree)h.postDelayed(()->listen(),700);});player.prepare();player.start();}catch(Exception e){localSpeak(f.getName());}}
    private void localSpeak(String text){if(tts==null)return;try{tts.setLanguage(arabic(text)?new Locale("ar","EG"):Locale.US);tts.setPitch(.72f);tts.setSpeechRate(.96f);tts.speak(text,TextToSpeech.QUEUE_FLUSH,null,"shadow");}catch(Exception ignored){stage("done");}}
    private boolean arabic(String s){for(int i=0;i<s.length();i++){char c=s.charAt(i);if(c>=0x0600&&c<=0x06FF)return true;}return false;}
    private void listen(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},MIC);return;}stage("listening");voice.start("ar-EG");}
    private void attach(){PopupMenu p=new PopupMenu(this,findViewById(android.R.id.content));p.getMenu().add("ملفات");p.getMenu().add("صور");p.getMenu().add("كاميرا");p.setOnMenuItemClickListener(i->{String n=i.getTitle().toString();if(n.equals("ملفات")){Intent x=new Intent(Intent.ACTION_OPEN_DOCUMENT);x.addCategory(Intent.CATEGORY_OPENABLE);x.setType("*/*");startActivityForResult(x,FILE);}else if(n.equals("صور")){Intent x=new Intent(Intent.ACTION_PICK);x.setType("image/*");startActivityForResult(x,FILE);}else try{startActivityForResult(new Intent(android.provider.MediaStore.ACTION_IMAGE_CAPTURE),CAMERA);}catch(Exception e){system("الكاميرا مش متاحة على الجهاز.");}return true;});p.show();}
    private void features(){PopupMenu p=new PopupMenu(this,findViewById(android.R.id.content));String[] a={"📺 ريموت TV","❄️ ريموت AC","🔎 قدرات الريموت","🌐 بحث أونلاين","🎨 توليد صورة","📱 تحكم عميق بالموبايل","🧠 Development Agent","🧠 الذاكرة","📊 حالة النظام","⚙ الإعدادات"};for(String s:a)p.getMenu().add(s);p.setOnMenuItemClickListener(i->{String n=i.getTitle().toString();if(n.startsWith("📺")||n.startsWith("❄️")||n.startsWith("🔎"))remotes.showCenter();else if(n.startsWith("📱"))startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS));else if(n.startsWith("🌐")){input.setText("ابحث أونلاين عن ");input.requestFocus();}else if(n.startsWith("🎨")){input.setText("اعملي صورة لـ ");input.requestFocus();}else if(n.startsWith("🧠 Development")){assistant("أنا جاهز لتحليل المشروع ووضع خطة تنفيذ. تنفيذ تعديلات GitHub نفسه يحتاج صلاحية كتابة صريحة.");}else if(n.equals("📊 حالة النظام"))assistant(core.handle("status"));else if(n.startsWith("⚙"))startActivity(new Intent(Settings.ACTION_SETTINGS));return true;});p.show();}
    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result==RESULT_OK&&data!=null)system("اتضاف: "+(data.getData()!=null?String.valueOf(data.getData().getLastPathSegment()):"صورة من الكاميرا"));}
    @Override public void onInit(int c){if(tts!=null){tts.setLanguage(new Locale("ar","EG"));tts.setPitch(.72f);tts.setSpeechRate(.96f);tts.setOnUtteranceProgressListener(new UtteranceProgressListener(){public void onStart(String id){}public void onDone(String id){runOnUiThread(()->{stage("done");if(handsFree)h.postDelayed(()->listen(),700);});}public void onError(String id){}});}}
    @Override protected void onDestroy(){handsFree=false;h.removeCallbacksAndMessages(null);voice.stop();if(player!=null)player.release();if(tts!=null){tts.stop();tts.shutdown();}super.onDestroy();}
}
