package com.shadow.mobile;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.BitmapFactory;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.media.MediaPlayer;
import android.os.Bundle;
import android.provider.Settings;
import android.view.*;
import android.view.inputmethod.EditorInfo;
import android.widget.*;
import android.speech.tts.TextToSpeech;
import java.io.*;
import java.util.*;

/** MOD-48.6: Online is the primary path. Text output is default; voice output is explicitly user-controlled. */
public class JarvisMainActivity extends Activity implements TextToSpeech.OnInitListener {
    private static final int MIC=801,FILE=802,CAMERA=803;
    private final int BG=Color.rgb(13,14,17),SURFACE=Color.rgb(29,31,36),SURFACE2=Color.rgb(42,44,51),TEXT=Color.rgb(241,243,246),MUTED=Color.rgb(155,160,170);
    private ShadowCore core; private ShadowCloudClient cloud; private ShadowVoiceRecognizer voice; private ShadowRemoteController remotes; private LinearLayout messages; private EditText input; private ShadowStatusView status; private TextToSpeech tts; private MediaPlayer player; private boolean conversation=true, cloudOnline;
    private boolean voiceOutput=false;
    private int dp(float n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
    private GradientDrawable bg(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
    private TextView tv(String s,float z){TextView v=new TextView(this);v.setText(s);v.setTextColor(TEXT);v.setTextSize(z);return v;}
    private void stage(String s){if(status!=null)status.setText(ShadowProcessIndicators.render(s));}
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);core=new ShadowCore(this);cloud=new ShadowCloudClient(this);remotes=new ShadowRemoteController(this);voice=new ShadowVoiceRecognizer(this,new ShadowVoiceRecognizer.Listener(){public void onListening(){runOnUiThread(()->stage("listening"));}public void onText(String t){runOnUiThread(()->{input.setText(t);send();});}public void onError(String m){runOnUiThread(()->system(m));}});tts=new TextToSpeech(this,this);ui();check();}
    private void ui(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setPadding(dp(8),dp(4),dp(8),dp(5));
        LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.setPadding(dp(4),dp(4),dp(4),dp(4));TextView menu=tv("☰",24);menu.setGravity(Gravity.CENTER);head.addView(menu,new LinearLayout.LayoutParams(dp(48),dp(52)));ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.shadow_logo);logo.setPadding(dp(8),dp(8),dp(8),dp(8));head.addView(logo,new LinearLayout.LayoutParams(dp(50),dp(52)));LinearLayout tb=new LinearLayout(this);tb.setOrientation(LinearLayout.VERTICAL);tb.setGravity(Gravity.CENTER);TextView title=tv("SHADOW",18);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);tb.addView(title);status=new ShadowStatusView(this);status.setTextColor(Color.rgb(112,210,160));status.setTextSize(11);status.setGravity(Gravity.CENTER);stage("thinking");tb.addView(status);head.addView(tb,new LinearLayout.LayoutParams(0,dp(52),1));TextView more=tv("⋮",26);more.setGravity(Gravity.CENTER);head.addView(more,new LinearLayout.LayoutParams(dp(48),dp(52)));root.addView(head);
        ScrollView sc=new ScrollView(this);sc.setFillViewport(true);messages=new LinearLayout(this);messages.setOrientation(LinearLayout.VERTICAL);messages.setPadding(dp(12),dp(10),dp(12),dp(18));sc.addView(messages);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));assistant("أهلاً محمد 👋\nأنا SHADOW — Z.\nأونلاين هو الوضع الأساسي: AI / Web / Images.\nالرد كتابة افتراضيًا. قل: رد صوتي — لتشغيل الصوت.");
        LinearLayout wrap=new LinearLayout(this);wrap.setGravity(Gravity.CENTER_VERTICAL);wrap.setPadding(dp(5),dp(3),dp(5),dp(3));wrap.setBackground(bg(SURFACE,24));TextView plus=tv("＋",25);plus.setGravity(Gravity.CENTER);wrap.addView(plus,new LinearLayout.LayoutParams(dp(48),dp(56)));input=new EditText(this);input.setHint("Message SHADOW");input.setHintTextColor(MUTED);input.setTextColor(TEXT);input.setTextSize(16);input.setMaxLines(5);input.setSingleLine(false);input.setBackgroundColor(Color.TRANSPARENT);wrap.addView(input,new LinearLayout.LayoutParams(0,dp(56),1));TextView mic=tv("🎙",24);mic.setGravity(Gravity.CENTER);wrap.addView(mic,new LinearLayout.LayoutParams(dp(52),dp(56)));TextView send=tv("➤",23);send.setGravity(Gravity.CENTER);wrap.addView(send,new LinearLayout.LayoutParams(dp(52),dp(56)));root.addView(wrap,new LinearLayout.LayoutParams(-1,dp(64)));TextView hint=tv("＋ Files/Photos/Camera  •  🎙 Voice input  •  Web Search",10);hint.setTextColor(MUTED);hint.setGravity(Gravity.CENTER);root.addView(hint,new LinearLayout.LayoutParams(-1,dp(24)));setContentView(root);
        menu.setOnClickListener(v->attach());more.setOnClickListener(v->features());plus.setOnClickListener(v->attach());mic.setOnClickListener(v->listen());send.setOnClickListener(v->send());input.setOnEditorActionListener((v,a,e)->{if(a==EditorInfo.IME_ACTION_SEND){send();return true;}return false;});}
    private void user(String s){TextView v=tv(s,16);v.setPadding(dp(14),dp(9),dp(14),dp(9));v.setBackground(bg(SURFACE2,18));messages.addView(v);bottom();}
    private void assistant(String s){TextView v=tv(s,16);v.setPadding(0,dp(8),dp(18),dp(8));v.setAutoLinkMask(android.text.util.Linkify.WEB_URLS);messages.addView(v);bottom();}
    private void system(String s){TextView v=tv(s,11);v.setTextColor(MUTED);messages.addView(v);bottom();}
    private void bottom(){messages.post(()->{ViewParent p=messages.getParent();if(p instanceof ScrollView)((ScrollView)p).fullScroll(View.FOCUS_DOWN);});}
    private void check(){new Thread(()->{cloudOnline=cloud.health();runOnUiThread(()->stage(cloudOnline?"online":"reconnecting"));}).start();}
    private boolean handleOutputCommand(String s){String x=s.trim().toLowerCase(Locale.ROOT);if(x.equals("رد كتابة")||x.equals("رد كتابه")||x.equals("من غير صوت")||x.equals("بدون صوت")||x.equals("text only")||x.equals("text response")){voiceOutput=false;assistant("تم — هرد كتابة فقط من دلوقتي.");stage("done");return true;}if(x.equals("رد صوتي")||x.equals("شغل الصوت")||x.equals("شغّل الصوت")||x.equals("voice on")||x.equals("voice response")){voiceOutput=true;assistant("تم — الصوت اتفعّل.");speak("تم — الصوت اتفعّل.");stage("done");return true;}return false;}
    private void send(){String s=input.getText().toString().trim();if(s.isEmpty())return;user(s);input.setText("");if(handleOutputCommand(s))return;stage("thinking");
        String local=ShadowPhoneController.execute(this,s);if(local!=null){stage("executing");assistant(local);speak(local);stage("done");return;}
        String governedLocal=null;try{governedLocal=core.handle(s);}catch(Throwable ignored){}if(governedLocal!=null&&!governedLocal.trim().isEmpty()){stage("executing");assistant(governedLocal);speak(governedLocal);stage("done");return;}
        if(isImage(s)){stage("designing");generateImage(s);return;}
        stage("online");new Thread(()->{try{ShadowCloudClient.CloudReply r=cloud.chat(s);cloudOnline=true;runOnUiThread(()->{stage("analyzing");assistant(r.answer);speak(r.answer);stage("online");});}catch(Throwable e){cloudOnline=false;String a;try{a=core.handle(s);}catch(Throwable ignored){a=null;}if(a==null||a.trim().isEmpty())a=core.offlineChat(s);String answer=a;runOnUiThread(()->{assistant(answer);stage("reconnecting");speak(answer);});}}).start();}
    private boolean isImage(String s){String x=s.toLowerCase(Locale.ROOT);return x.contains("صمم صورة")||x.contains("اعمل صورة")||x.contains("صورة لـ")||x.contains("generate image")||x.contains("create an image")||x.contains("design an image");}
    private void generateImage(String prompt){system("SHADOW • بيصمم الصورة أونلاين…");new Thread(()->{try{String b64=cloud.generateImage(prompt);byte[] data=android.util.Base64.decode(b64,android.util.Base64.DEFAULT);runOnUiThread(()->{ImageView image=new ImageView(this);image.setAdjustViewBounds(true);image.setScaleType(ImageView.ScaleType.CENTER_CROP);image.setImageBitmap(BitmapFactory.decodeStream(new ByteArrayInputStream(data)));messages.addView(image,new LinearLayout.LayoutParams(-1,dp(320)));assistant("اتفضل — الصورة جاهزة.");stage("online");});}catch(Throwable e){runOnUiThread(()->{assistant("مش قادر أولّد الصورة دلوقتي: "+e.getMessage());stage("reconnecting");});}}).start();}
    private void attach(){PopupMenu p=new PopupMenu(this,findViewById(android.R.id.content));p.getMenu().add("Files");p.getMenu().add("Photos");p.getMenu().add("Camera");p.setOnMenuItemClickListener(i->{String n=i.getTitle().toString();if(n.equals("Files")){Intent x=new Intent(Intent.ACTION_OPEN_DOCUMENT);x.addCategory(Intent.CATEGORY_OPENABLE);x.setType("*/*");startActivityForResult(x,FILE);}else if(n.equals("Photos")){Intent x=new Intent(Intent.ACTION_PICK);x.setType("image/*");startActivityForResult(x,FILE);}else{try{startActivityForResult(new Intent(android.provider.MediaStore.ACTION_IMAGE_CAPTURE),CAMERA);}catch(Exception e){system("No camera application is available.");}}return true;});p.show();}
    private void features(){PopupMenu p=new PopupMenu(this,findViewById(android.R.id.content));String[] a={"📺 TV Remote","❄️ AC Remote","🔎 Remote capabilities","🌐 Web search","🎨 Image design","📱 Deep phone control","🧠 Development Agent","Profile / Memory","System status","Settings"};for(String s:a)p.getMenu().add(s);p.setOnMenuItemClickListener(i->{String n=i.getTitle().toString();if(n.startsWith("📺")||n.startsWith("❄️")||n.startsWith("🔎"))remotes.showCenter();else if(n.startsWith("📱"))startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS));else if(n.startsWith("🌐")){input.setText("ابحث أونلاين عن ");input.requestFocus();}else if(n.startsWith("🎨")){input.setText("صمم صورة: ");input.requestFocus();}else if(n.startsWith("🧠"))system("Development Agent: analyze → plan → approve → edit → test → report");else if(n.equals("System status"))assistant(core.handle("status"));else if(n.equals("Settings"))startActivity(new Intent(Settings.ACTION_SETTINGS));return true;});p.show();}
    private void listen(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},MIC);return;}stage("listening");voice.start("ar-EG");}
    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result==RESULT_OK&&data!=null)system("Attached: "+(data.getData()!=null?String.valueOf(data.getData().getLastPathSegment()):"camera capture"));}
    private boolean arabic(String s){for(int i=0;i<s.length();i++){char c=s.charAt(i);if(c>=0x0600&&c<=0x06FF)return true;}return false;}
    private void speak(String s){if(!voiceOutput||s==null||s.trim().isEmpty())return;if(cloudOnline)new Thread(()->{try{byte[] audio=cloud.synthesizeSpeech(s);File f=new File(getCacheDir(),"shadow_voice.mp3");try(FileOutputStream o=new FileOutputStream(f)){o.write(audio);}runOnUiThread(()->play(f));}catch(Exception e){runOnUiThread(()->localSpeak(s));}}).start();else localSpeak(s);}
    private void play(File f){try{if(player!=null)player.release();player=new MediaPlayer();player.setDataSource(f.getAbsolutePath());player.setOnCompletionListener(m->{m.release();player=null;});player.prepare();player.start();}catch(Exception e){localSpeak("حصلت مشكلة في الصوت.");}}
    private void localSpeak(String s){if(tts==null||!voiceOutput)return;try{tts.setLanguage(arabic(s)?new Locale("ar","EG"):Locale.US);tts.setPitch(.72f);tts.setSpeechRate(.96f);tts.speak(s,TextToSpeech.QUEUE_FLUSH,null,"shadow");}catch(Exception ignored){}}
    @Override public void onInit(int c){if(tts!=null){tts.setLanguage(new Locale("ar","EG"));tts.setPitch(.72f);}}
    @Override protected void onDestroy(){voice.stop();if(player!=null)player.release();if(tts!=null){tts.stop();tts.shutdown();}super.onDestroy();}
}
